# Generated by Django 4.2.3 on 2024-07-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_alter_user_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_No',
            field=models.CharField(max_length=150),
        ),
    ]
