# Generated by Django 4.2.3 on 2024-07-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0006_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
