# Generated by Django 4.2.3 on 2024-06-24 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_flashsell_offer_remove_product_attributes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stock', models.IntegerField(blank=True, default=0, null=True)),
                ('sold', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product', to='product.product')),
            ],
        ),
    ]
