# Generated by Django 4.2.3 on 2024-06-24 06:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_attributevalue_product_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=product.models.default_end_date)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_image_first', models.ImageField(upload_to='offerimage/')),
                ('offer_image_second', models.ImageField(upload_to='offerimage/')),
                ('offer_image_third', models.ImageField(blank=True, null=True, upload_to='offerimage/')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=product.models.default_end_date)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='stock',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.attributevalue'),
        ),
        migrations.AddField(
            model_name='stock',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='productimages/'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField()),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_id', to='product.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_product', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='FlashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField(blank=True, null=True)),
                ('flash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashid', to='product.flashsell')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_product', to='product.product')),
            ],
        ),
    ]
