# Generated by Django 4.2.3 on 2024-06-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_flashsell_offer_remove_product_attributes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
