# Generated by Django 4.2.3 on 2024-06-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_stock_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='addprice',
        ),
    ]
