# Generated by Django 4.2.3 on 2024-06-28 05:48

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_category_name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='childcategoryimage/')),
                ('ordering', models.PositiveIntegerField()),
                ('child_category_slug', autoslug.fields.AutoSlugField(default=None, editable=False, unique=True, verbose_name=models.CharField(max_length=250))),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainCategories', to='product.category')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subCategories', to='product.subcategory')),
            ],
            options={
                'ordering': ['-ordering', '-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='child_sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='childcategory', to='product.childcategory'),
            preserve_default=False,
        ),
    ]
