# Generated by Django 4.2.3 on 2024-06-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childcategory',
            name='category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mainCategory', to='product.category'),
            preserve_default=False,
        ),
    ]
