# Generated by Django 4.2.3 on 2024-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_bannar_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
