# Generated by Django 4.2.3 on 2024-07-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_product_description'),
        ('product', '0014_rename_id_popular_product_is_popular'),
    ]

    operations = [
    ]
